rpc:
  userAddress: 127.0.0.1:9000

mysql:
  address: 127.0.0.1:3306
  username: root
  password: 123456
  database: chatim
  maxOpenConn: 1000
  maxIdleConn: 100
  maxLifeTime: 60
  logLevel: 4
  slowThreshold: 500

redis:
  address:
    - 127.0.0.1:6379
  username:
  password:

rabbitmq:
  address: 127.0.0.1:5672
  username: guest
  password: guest